import { NextRequest, NextResponse } from 'next/server';
import createMiddleware from 'next-intl/middleware';
import { routing } from './i18n/routing';

const intlMiddleware = createMiddleware(routing);

// Pages that exist outside [locale] routing — don't redirect them.
// Includes Next.js metadata image routes generated by icon.tsx / apple-icon.tsx
const NON_LOCALE_PATHS = ['/contact', '/icon', '/apple-icon', '/opengraph-image'];

export default function middleware(request: NextRequest) {
  const pathname = request.nextUrl.pathname;

  // Skip locale redirect for pages that live at root (not under [locale])
  if (NON_LOCALE_PATHS.some(p => pathname === p || pathname.startsWith(p + '/'))) {
    return NextResponse.next();
  }

  return intlMiddleware(request);
}

export const config = {
  matcher: ['/((?!_next|_vercel|.*\\..*).*)']
};
